# Generated by Django 4.2.3 on 2023-09-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
